name: SahajSoftware
favicon: null
layout_spectrum: 0.9190126804169267
typography_spectrum: 0.2273427527397871
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.45283312513493
  lightness: 0.4400412105023861
  saturation: 0.848514903569594
  rhythmicContrast: 0.9594803343061358
purpose: []
